name: "cqrs-backend"

services:
  pgadmin:
    image: dpage/pgadmin4:9.8
    ports:
      - 5050:80
    env_file: ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - backend_pgadmin_data:/var/lib/pgadmin
    networks:
      - cqrs_network

  database:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - backend_postgres_data:/var/lib/postgresql/data
    networks:
      - cqrs_network

  backend:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "8090:8090"
    env_file: ./.env
    networks:
      - cqrs_network

volumes:
  backend_postgres_data: {}
  backend_pgadmin_data: {}

networks:
  cqrs_network:
    driver: bridge